# Generated by Django 3.1.2 on 2020-10-29 04:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.IntegerField(primary_key=True, serialize=False)),
                ('name_client', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('user_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('email_client', models.EmailField(max_length=60)),
                ('is_active', models.BooleanField()),
                ('control_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name_client', 'category', 'country', 'city', 'user_created'],
            },
        ),
    ]
