# Generated by Django 3.1.2 on 2020-10-29 22:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_client', models.IntegerField(primary_key=True, serialize=False)),
                ('name_client', models.CharField(max_length=50, verbose_name='Nombre')),
                ('country', models.CharField(max_length=50, verbose_name='Pais')),
                ('city', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('category', models.CharField(choices=[('TEC', 'Tecnología'), ('HEA', 'Salud'), ('MOG', 'Minería, petróleo y gas'), ('FIN', 'Financiero'), ('FOO', 'Alimento'), ('TRA', 'Tranporte')], default='TEC', max_length=20, verbose_name='Categoría')),
                ('user_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('email_client', models.EmailField(max_length=60, unique=True, verbose_name='e-mail')),
                ('is_active', models.BooleanField(verbose_name='Estado Activo')),
                ('control_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Contrato')),
            ],
            options={
                'ordering': ['name_client', 'category', 'country', 'city', 'user_created'],
            },
        ),
    ]
